language: node_js
node_js: node
services: xvfb

script:
  - npm run ci

after_success:
  - npm run cov && npx codecov

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master