language: node_js
node_js: '12'
services: xvfb

script:
  - npm run ci || npm run cov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master