version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Workaround for GoogleChrome/puppeteer#290
          command: 'sh .circleci/setup_puppeteer.sh'

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir .nyc_output && chown -R $USER:$USER .nyc_output
      - run: touch .nyc_output/out.json && chown -R $USER:$USER .nyc_output/out.json
      - run: mkdir coverage && chown -R $USER:$USER coverage
      - run: touch coverage/lcov.info && chown -R $USER:$USER coverage/lcov.info

      - run: npm run ci && npx codecov

      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage/lcov.info
      - store_test_results:
          path: .nyc_output
      - store_artifacts:
          path: .nyc_output/out.json